#!/bin/bash

echo '############################################################'
echo '# Building fully Babelified CommonJS version of the module #'
echo '############################################################'
yarn run build:lib

echo '############################################################'
echo '#    Building fully Babelified ES version of the module    #'
echo '############################################################'
yarn run build:es
